# Generated by Django 2.0.4 on 2018-04-08 11:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Md5Task',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('result', models.TextField(null=True)),
                ('has_error', models.BooleanField(default=False)),
            ],
        ),
    ]
